# Dependencies
markdown:         CommonMarkGhPages
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Claire Gregg
description:      'Recent Computer Science Grad.'

author:
  name:           'Claire Gregg'
