# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Claire Gregg
description:      '4th Year Computer Science student.'
url:              http://clairegregg.com
baseurl:          / 

author:
  name:           'Claire Gregg'
