# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Claire Gregg
description:      '4th Year Computer Science student.'

author:
  name:           'Claire Gregg'
